### ISSUE TITLE
AreaBrick Image not working as intended

### ISSUE THREAD

**Issue by roland4432** [dachcom-digital/pimcore-toolbox#102]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

Image from your collection does not follow pimcore defaults. Since it is not rendering the correct class passed to the element (e.g. img-fluid) nor is it using the right config for getting the corresponding thumbnail-images.

(While debugging your code, the code for rendering the right HTML is ran twice. First time with all the correct settings and in the second loop without (img-) class information or the needed src-set.)

**Comment by solverat** [comment]
Hey @roland4432, thanks for your investigation. You're absolutely right, the class has never been injected into the thumbnail configuration. I just fixed [that](https://github.com/dachcom-digital/pimcore-toolbox/commit/9283b297c5eef0b895ca248a9b259cc62577ae8c)).

About the second part:
 > "nor is it using the right config for getting the corresponding thumbnail-images." 

I'm afraid but i think i don't get it. I tested it and the html (incl. srcset) rendering works just fine. Could you help me out?

**Comment by roland4432** [comment]
I will setup a testcontainer the next days. Since it's been three weeks ago now, I am not sure if I had a thumbnail config at all in the project.
I'll catch you later this week.

Thanks for the update so far ;)

**Comment by solverat** [comment]
merged. feel free to reopen this issue again if there is still something missing.
