### ISSUE TITLE
Problem in Editmode with VueJS enabled

### ISSUE THREAD

**Issue by davidhoeck** [dachcom-digital/pimcore-toolbox#110]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| BC Break report? | no
| RFC?             | no

Because the Toolbox places `<script>` tag within the container on which Vue is mounted, the whole bundle does not work in editmode anymore. What approach should we take - disabling Vue in Editmode is no option.

**Comment by solverat** [comment]
The script tag gets generated by pimcore, if you're talking about this snippet here:

![image](https://user-images.githubusercontent.com/700119/58235589-64dc0d80-7d41-11e9-81e4-d24a53ff0ab2.png)

So, there is no way to remove it - besides of not using any pimcore brick element at all. :)

**Comment by davidhoeck** [comment]
@solverat exactly that... so I need to close this one here and open on in the pimcore repository :D

**Comment by mrpdean** [comment]
@davidhoeck   Hi David, I know this is an old issue but were you ever able to solve it?  I couldn't spot any issues relating to this on the Pimcore repo and I'm now facing the same problem.  Thanks

**Comment by davidhoeck** [comment]
@mrpdean currently there is no other solution then disabling vue in the editmode. maybe there would be a way to collect the script tags and defer the rendering process, so that you can output at the end of the body. I do not understand why Pimcore is doing it that way, especially in the times of Vue, React etc.
