### ISSUE TITLE
[WYSIWYG] Unable to edit link (button style) in Safari

### ISSUE THREAD

**Issue by plexmaniax** [dachcom-digital/pimcore-toolbox#111]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

It`s not possible to edit Links (Button Style) in Safari, you couldn`t mark the link to edit.
Tested with Safari Version 12.1.1 (14607.2.6.1.1) on different projects

**Comment by solverat** [comment]
Unable to reproduce it. Please provide some more information (eg. screenshot).
***
Note: It's probably a ckeditor issue.

**Comment by solverat** [comment]
close due inactivity
