### ISSUE TITLE
Update to support Pimcore 6

### ISSUE THREAD

**Issue by dpfaffenbauer** [dachcom-digital/pimcore-toolbox#112]
| Q                | A
| ---------------- | -----
| Bug report?      | yes/no
| Feature request? | yes/no
| BC Break report? | yes/no
| RFC?             | yes/no

**Comment by msphn** [comment]
@dpfaffenbauer something else to do here?

**Comment by dpfaffenbauer** [comment]
I don’t know, but don’t think so

**Comment by msphn** [comment]
For me it works with Pimcore 6. I would consider it done? 👍
