### ISSUE TITLE
Bug with more than 2 col-half elements in Toolbox Element Configuration

### ISSUE THREAD

**Issue by christopher-siegel** [dachcom-digital/pimcore-toolbox#134]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes/no

When adding selects for e.g. `additionalClasses` you can adjust the width of the element with 

```
additional_classes:
    type: additionalClasses
    title: 'Style'
    col_class: 't-col-half'
```

When using more than 2 (or in case of t-col-third more than 3) of those elements after each other, it renders incorrectly:

![bug](https://user-images.githubusercontent.com/2526628/76069001-7cb01580-5f92-11ea-90e2-7aaa10712fc8.png)
_**Before:** Half columns render incorrectly after 2 elements._

The code only checked if exactly 2 elements with t-col-half followed each other and only then included a t-row clearfix which renders the "line break".

I will be providing a PR which fixes the issue by using twigs modulo `is divisible by(2)` and is `divisible by(3)` to account for more than 2 or 3 half or third columns:

![fixed](https://user-images.githubusercontent.com/2526628/76069117-a8330000-5f92-11ea-88b6-fe0626ba8616.png)
_**After:** Half columns render correctly, adding a line break after every 2 elements._

**Comment by christopher-siegel** [comment]
@solverat Any comments on this small fix? 
(also i don't get why the build is failing, seems to be an issue with the 2.8 branch in general as my fix changes nothing that should break anything)

**Comment by solverat** [comment]
@christopher-siegel Thanks. I'll keep the issue open to 

- port to dev-master
- update readme
