### ISSUE TITLE
[TB4] Pimcore X Area Bricks

### ISSUE THREAD

**Issue by solverat** [dachcom-digital/pimcore-toolbox#143]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

With Pimcore 7, editables configuration changed completely by using properties for areabricks instead of inline forms  (https://github.com/pimcore/pimcore/issues/6370).

Configuration Example: https://github.com/pimcore/pimcore/pull/6923#issuecomment-671257112

## Migration

- Add `getEditableDialogBoxConfiguration ` to `ToolboxBundle\Document\Areabrick\AbstractAreabrick` which should generate the configuration based on existing toolbox yaml configs. 
- It should be possible to override this method and skip the yaml configuration part

**Comment by Brainshaker95** [comment]
@solverat 

The deprecated usage of Tags should also be replaced with Editables.
The usage of the views ParameterBag should also be replaced since the `getView` function of `Info` is deprecated.

Example (pimcore-toolbox/src/ToolboxBundle/Document/Areabrick/Accordion/Accordion.php):

```php
<?php

namespace ToolboxBundle\Document\Areabrick\Accordion;

use ToolboxBundle\Document\Areabrick\AbstractAreabrick;
// current: use Pimcore\Model\Document\Tag\Area\Info;
use Pimcore\Model\Document\Editable\Area\Info;

class Accordion extends AbstractAreabrick
{
    /**
     * {@inheritdoc}
     */
    public function action(Info $info)
    {
        parent::action($info);

        $infoParams = $info->getParams();
        if (isset($infoParams['toolboxAccordionId'])) {
            $id = $infoParams['toolboxAccordionId'];
        } else {
            $id = uniqid('accordion-');
        }

        // current: $info->getView()->getParameters()->add(['id' => $id]);
        $info->setParam('id', $id);

        return null;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'Accordion';
    }

    /**
     * @return string
     */
    public function getDescription()
    {
        return 'Toolbox Accordion / Tabs';
    }
}
```

**Comment by jeykodev** [comment]
@solverat any progress on this topic? We heavily use the toolbox in our projects. As we now have the first Pimcore X projects on our table this Pimcore X support ist urgently awaited. :)

**Comment by solverat** [comment]
I just published the last minor version 3.3. Next step: Pimcore X!

**Comment by foxgreek** [comment]
@solverat any news for Pimcore X?

**Comment by solverat** [comment]
@foxgreek In progress, see #160.

**Comment by solverat** [comment]
Although we still don't recommend PX within frontend editing due to serious open issues (Examples: https://github.com/pimcore/pimcore/issues/10474, https://github.com/pimcore/pimcore/issues/10307) we're now going to publish 4.0 because we have to start somewhere, right? :)
