### ISSUE TITLE
On changing map zoom getting error InvalidValueError: setZoom: not a number in google map toolbox

### ISSUE THREAD

**Issue by pdchaudhary** [dachcom-digital/pimcore-toolbox#146]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no

Pimcore Version : 6.8.5
Getting InvalidValueError: setZoom: not a number in google map toolbox while changing map zoom otherwise it is working fine.

**Comment by jmbs-es** [comment]
Thanks for fixing the bug!
