### ISSUE TITLE
Google Maps Locations breaks with single quotes

### ISSUE THREAD

**Issue by luca-mussoni-extera** [dachcom-digital/pimcore-toolbox#151]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

If there's a single quote in any field of the "Locations" section in Google Maps brick, the resulting HTML is broken, as special characters are not encoded.

![Screenshot 2021-03-15 at 12 24 50](https://user-images.githubusercontent.com/56717120/111149565-52256f00-858d-11eb-867e-4348a1fc8941.png)

![Screenshot 2021-03-15 at 12 27 18](https://user-images.githubusercontent.com/56717120/111149582-56ea2300-858d-11eb-8680-57a2bb16a3aa.png)

![Screenshot 2021-03-15 at 12 27 31](https://user-images.githubusercontent.com/56717120/111165679-9e79aa80-859f-11eb-94a2-eaa36e3057a6.png)

**Comment by solverat** [comment]
fixed
