### ISSUE TITLE
[TB4] Add Editable Permissions

### ISSUE THREAD

**Issue by solverat** [dachcom-digital/pimcore-toolbox#161]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Add each editable to the permission window:
![image](https://user-images.githubusercontent.com/700119/135221841-89baa973-eb54-4452-9e39-84c9c99cadca.png)

- Add permission via compiler pass while rebuilding container 
- Do not remove editable from view but add an fixed overlay to each editable which is not allowed to edit

**Comment by dpfaffenbauer** [comment]
@solverat Is it on purpose that every new brick also needs a change of permissions at user/role levels? I just migrated to Pimcore X with that change and saw these new permissions. I have about 20 roles and 200 users with 60 bricks, quite a hassle to change these permissions :D.

I am overriding the PermissionManager for now, but wouldn't it be better to just have a configuration that defines the default behaviour?
