### ISSUE TITLE
Minify issue

### ISSUE THREAD

**Issue by pagliaso** [dachcom-digital/pimcore-toolbox#18]
Hi,

I have just installed your plugin and I get an error:

 Fatal error: Class 'MatthiasMullie\Minify\CSS' not found in /home/astilleroslagos/domains/gato.astilleroslagos.es/public_html/plugins/Toolbox/lib/Toolbox/Controller/Minify/Builder.php on line 37

Do I need to install something else?

Many thanks in advance for your help and kind regards from Spain,

Alb

**Comment by solverat** [comment]
Please check the requirements in the [composer.json](https://github.com/dachcom-digital/pimcore-toolbox/blob/master/composer.json) file. Install the plugin via composer would be the simplest thing.

**Comment by pagliaso** [comment]
Many thanks,

I have just installed your plugin using composed as you proposed and I think it is fine now.

Before I installed manually.

Thanks and kind regards,
