### ISSUE TITLE
PermissionListener - should not need a Database Connection on cache:clear

### ISSUE THREAD

**Issue by dpfaffenbauer** [dachcom-digital/pimcore-toolbox#181]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? |no
| BC Break report? |no
| RFC?             |no

Database might not be available during that time

**Comment by solverat** [comment]
Done with #187

**Comment by dpfaffenbauer** [comment]
Thanks @solverat. Just note that this is a BC since it removes a file. We basically remove that service (command) in our app to make it work

**Comment by solverat** [comment]
It is too late. I hope it will not cause too many problems for you, and hopefully no one else has removed this service.
