### ISSUE TITLE
Can´t install toolkit - please help. 

### ISSUE THREAD

**Issue by mozbs** [dachcom-digital/pimcore-toolbox#184]
Hi guys, 

installing pimcore extensions seems so diffenrent. Can somebody tell me, where to put this snippet:
"require" : {
    "dachcom-digital/toolbox" : "~4.0.0"
}

Or do you have a short description for me. Implementing toolkit ist very iomportant for me. 

Thank you very much and best regards

Marc

**Comment by solverat** [comment]
@mozbs These are very basics when you're working in a PHP ecosystem. We're sorry, but we can't provide any beginner tutorials regarding your setup.
