### ISSUE TITLE
human-readable filesize

### ISSUE THREAD

**Issue by benwalch** [dachcom-digital/pimcore-toolbox#204]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

The calculation for human-readable file sizes is wrong for specific cases.
For example, a file having 1033760 bytes (~ 1 MB) will be displayed as "1 KB"

**Comment by solverat** [comment]
fixed with #205, #206 .
