### ISSUE TITLE
Render Areas within a Bundle

### ISSUE THREAD

**Issue by daniel-travix** [dachcom-digital/pimcore-toolbox#37]
Hi,

when i create a new custom Bundle and follow your instructions for a new custom brick, my custom Area will not render, becuase i have to put it in /app/Resources/views/Areas/

How is it possible to get it work within /src/Company/testBundle/Resources/views/Areas/?

Any idea would be nice  :)

**Comment by solverat** [comment]
yes, this is possible. i just updated the docs. hope this helps: https://github.com/dachcom-digital/pimcore-toolbox/blob/master/docs/10_CustomBricks.md#adding-bricks-from-bundles
