### ISSUE TITLE
Add icons or possibility to provide custom icons

### ISSUE THREAD

**Issue by gadget60** [dachcom-digital/pimcore-toolbox#52]
Would you mind adding some nice icons for the bricks provided by Toolbox (in /src/ToolboxBundle/Resources/public/app/[brick]/icon.png)?
Or maybe add a config section to customize the icon paths?

The auto-selected icons are pretty meaningless - it would be nice if they were not just selected randomly. Unfortunately I don't see a proper way to override the icon paths, since Pimcore by default is looking in the Bundle's public path only:
https://github.com/pimcore/pimcore/blob/296d0871ae191e2095256a1fbc9fcbfd32d97a5d/pimcore/lib/Pimcore/Document/Tag/TagHandler.php#L169

**Comment by solverat** [comment]
that's a good point. will look into it.

**Comment by solverat** [comment]
Hey @gadget60. I just implemented some default icons (see image), if you need to add a icon to your custom brick, just add this to your area controller:
```php
public function getIcon()
{
        return '/static/areas/brickname/icon.svg';
}
```
## preview
<img width="232" alt="bildschirmfoto 2018-01-28 um 17 22 21" src="https://user-images.githubusercontent.com/700119/35484427-f37717b8-044f-11e8-9a80-519024c1e779.png">
