### ISSUE TITLE
Installation Error on Pimcore 5.1.1 build 184

### ISSUE THREAD

**Issue by dennistiboni-extera** [dachcom-digital/pimcore-toolbox#53]
Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "pimcore_system_config.services.google.browserapikey". You cannot access nested array items, do you want to inject "pimcore_system_config.services" instead? in /var/www/public_html/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php on line 102

**Comment by solverat** [comment]
hey @dennistiboni-extera, thats weird. this option is stored in pimcore backend.

In pimcore system settings to go to "google api key", enter some letters in "browser api key" and save:
![bildschirmfoto 2018-01-29 um 18 03 31](https://user-images.githubusercontent.com/700119/35523264-bc9af9c4-051e-11e8-8d5b-15c77c3bfbb5.png)

Please let me know if the message still appears.

**Comment by dennistiboni-extera** [comment]
Ciao @solverat  I had already solved by setting the browser api, but the installation is broken without this value and I wanted to report it.

**Comment by solverat** [comment]
hey @dennistiboni-extera, thanks anyway. i'll put a note to the upgrade hints.

**Comment by gadget60** [comment]
Hi @solverat! I'm running into the same issue here. Setting the API key in backend helps, however this is problematic because it forces manual interaction before being able to install/enable Toolbox. Otherwise even a "composer install" fails with the message above.

**Comment by solverat** [comment]
fixed in https://github.com/dachcom-digital/pimcore-toolbox/commit/d5b234e5d9b93847e58b78be23518e68ce614a5d.
