### ISSUE TITLE
Error: Areabrick image is already registered

### ISSUE THREAD

**Issue by aliw77** [dachcom-digital/pimcore-toolbox#54]
Added the require line to composer.json, ran composer update and tried to clear cache.  I see the error below:

```bash
In AreabrickManager.php line 100:

  Areabrick image is already registered as service ToolboxBundle\Document\Areabrick\Image\Image (trying to add service app.area.brick.image)
```
Pimcore 5.1.1 (kernel: app, env: prod, debug: false)
php 7.1
nginx

**Comment by solverat** [comment]
Looks like you already have an brick called "image" (`app.area.brick.image`). You need to rename your app brick to something different.
