### ISSUE TITLE
Pimcore 5.3.0 Adaptions

### ISSUE THREAD

**Issue by solverat** [dachcom-digital/pimcore-toolbox#70]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

Make Toolbox ready for Pimcore 5.3.0.

**Comment by dpfaffenbauer** [comment]
still not ready, there is no delete button:

![bildschirmfoto 2018-07-30 um 16 03 31](https://user-images.githubusercontent.com/5981845/43402087-1d8ba60c-9412-11e8-8b03-3ecff0fb3c51.png)
