### ISSUE TITLE
toolbox edit button and settings

### ISSUE THREAD

**Issue by l1ph** [dachcom-digital/pimcore-toolbox#80]
Hi i am new to pimcore and want to start my project with this toolbox.

I cant figure out how to see the content element settings like in this Screenshot below

![bildschirmfoto 2018-10-17 um 12 04 51](https://user-images.githubusercontent.com/9683604/47079174-17288100-d205-11e8-9a11-6aadce8fa7ae.png)

my view:
![bildschirmfoto 2018-10-17 um 12 03 44](https://user-images.githubusercontent.com/9683604/47079190-21e31600-d205-11e8-91f1-9705c09835e5.png)

thx for your help

**Comment by solverat** [comment]
Hi @l1ph, have you installed the ToolboxBundle in the Extension-Manager?

**Comment by solverat** [comment]
closed due to inactivity.
