### ISSUE TITLE
How to extend the configuration of ToolboxBundle?

### ISSUE THREAD

**Issue by fabiofabbrucci** [dachcom-digital/pimcore-toolbox#84]
Hi,
we used to use your great bundle in every project we start.
We observed that we tend to repeat some kind of settings (specific settings, overriding of some views). For this reason we decided to create a new bundle that extend this one.

```
<?php
namespace Extera\ToolboxBundle;
use Symfony\Component\HttpKernel\Bundle\Bundle;
class ExteraToolboxBundle extends Bundle
{
    public function getParent()
    {
        return 'ToolboxBundle';
    }
}
```

This worked well for overriding views 👍 
But when we tryed to override configuration (instead of doing it at the app-level) we got this error:

```
Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: There is no extension able to load the configuration for "toolbox" (in /var/www/html/src/Extera/ToolboxBundle/DependencyInjection/../Resources/config/toolbox.yml). Looked for namespace "toolbox", found none in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php on line 168

Symfony\Component\Config\Exception\FileLoaderLoadException: There is no extension able to load the configuration for "toolbox" (in /var/www/html/src/Extera/ToolboxBundle/DependencyInjection/../Resources/config/toolbox.yml). Looked for namespace "toolbox", found none in /var/www/html/src/Extera/ToolboxBundle/DependencyInjection/../Resources/config/toolbox.yml (which is being imported from "/var/www/html/src/Extera/ToolboxBundle/DependencyInjection/../Resources/config/services.yml"). in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/FileLoader.php on line 168
```

In order to find a solution, I got into [this](https://stackoverflow.com/questions/51320065/how-to-override-configuration-of-third-bundle-from-a-third-bundle) but it didn't work for me.
Do you have any suggestions on how we could override the configuration of this bundle?

Thanks :)

**Comment by solverat** [comment]
Hey @fabiofabbrucci, bundle inheritance is [deprecated](https://symfony.com/doc/3.4/bundles/inheritance.html) in symfony 3.4 and has been completely removed in symfony 4.0. So i would suggest to avoid this solution. Just go ahead with the standard [symfony template override philosophy](https://symfony.com/doc/3.4/bundles/override.html), if you have to.

**Comment by fabiofabbrucci** [comment]
Many thanks @solverat !!! <3
